name: Reusble Docker Build

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      dockerfile:
        required: false
        type: string
        default: Dockerfile
      context:
        required: false
        type: string
        default: "."
      build-args:
        required: false
        type: string
    outputs:
      container-uri:
        description: "URI of new image"
        value: ${{ jobs.docker-build.outputs.container-uri }}

jobs:
  docker-build:
    environment: dev
    runs-on: ubuntu-latest
    env:
      IMAGE_ORG: ghcr.io/${{ github.repository_owner }}
      IMAGE_REPO: ${{ inputs.image-name }}
    outputs:
      container-uri: ${{ steps.container.outputs.uri }}
    steps:
      # Pull the Dockerfile:
      - uses: actions/checkout@v4

      # Setup Docker Building on Actions:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Save Container Info
        id: container
        run: echo "uri=${{ env.IMAGE_ORG }}/${{ env.IMAGE_REPO }}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_OUTPUT

      # Actually Build it:
      - uses: docker/build-push-action@v5
        with:
          file: ${{ inputs.dockerfile }}
          context: ${{ inputs.context }}
          push: true
          pull: true         # Always pull the latest base image before building
          build-args: ${{ inputs.build-args }}
          tags: |
            ${{ steps.container.outputs.uri }}:${{ inputs.tagname || github.ref_name }}
            ${{ steps.container.outputs.uri }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max